import { createClientFromRequest } from 'npm:@base44/sdk@0.8.38';
import Anthropic from 'npm:@anthropic-ai/sdk';

/**
 * Byteling — designReview  (the "Designling" design-review mode)
 *
 * The same companion, in art-director mode. The extension captures the visible
 * tab + runs the style census, POSTs them here, and this returns a structured
 * critique. Called authenticated (widget/extension):
 *   base44.functions.invoke('designReview', { url, census, screenshotBase64 })
 *
 * - url:             the page under review (for context / the logo-swap framing)
 * - census:          JSON from style-census.js (the evidence layer) — may be null
 * - screenshotBase64: a data: URL screenshot of the page (JPEG ~q60) — may be null
 *   (at least one of census / screenshot must be present)
 *
 * Bring-your-own-key: the Anthropic key is the caller's own ProviderKey, resolved
 * under the service role — identical path to claude-chat. No new key handling.
 *
 * EPHEMERAL: the screenshot and census are never persisted. Only the returned
 * JSON verdict is the artifact, and even that is left to the caller to keep.
 *
 * THE DESIGN BIBLE below is GENERATED, not hand-written: `scripts/sync-design-bible.mjs`
 * re-reads the canonical checklist docs from claude-skills and rewrites the
 * DESIGN_BIBLE block, so the function always carries the CURRENT bible rather than
 * a drifting snapshot. Run the script whenever the bible/skills evolve, then
 * redeploy. Canonical sources:
 *   C:/Github/ARS/claude-skills/shared/build-bible/lessons/divine-hell-nos.md
 *   C:/Github/ARS/claude-skills/shared/build-bible/lessons/anti-ai-craft-tells.md
 *   C:/Github/ARS/claude-skills/shared/build-bible/junk-drawer/design-taste.md
 *   C:/Github/ARS/claude-skills/shared/build-bible/junk-drawer/ars-taste.md
 * The review CONTRACT (role, how to apply the layers, the JSON shape) is stable
 * and hand-maintained in DESIGN_REVIEW_SYSTEM below.
 */

const MODEL = 'claude-opus-4-8';
const MAX_TOKENS = 8000;   // room for adaptive thinking + the JSON verdict
const REVIEW_EFFORT = 'high'; // a deliberate one-shot critique — depth over speed
const MAX_CENSUS_CHARS = 14_000; // the census is already summarised; cap defensively

const IMG_TYPES = new Set(['image/png', 'image/jpeg', 'image/gif', 'image/webp']);
const MAX_IMG_B64 = 7_000_000; // ~5 MB decoded
function parseImageInput(raw: unknown): { media_type: string; data: string } | null {
  if (typeof raw !== 'string' || !raw) return null;
  const m = raw.match(/^data:(image\/[a-zA-Z+]+);base64,(.+)$/);
  if (!m) return null;
  const media_type = m[1].toLowerCase();
  const data = m[2];
  if (!IMG_TYPES.has(media_type) || data.length > MAX_IMG_B64) return null;
  return { media_type, data };
}

// <<<DESIGN_BIBLE (generated by scripts/sync-design-bible.mjs — do not hand-edit)>>>
const DESIGN_BIBLE = "The house design bible (current, synced from claude-skills). Use this as your rulebook.\n\n\n===== The divine hell-nos (DISCIPLINE — binding) =====\n# The divine hell nos\n\nThe thesis: the real distinction is not \"AI built it\" versus \"human built it.\" It is\n**generated versus authored**. Generated design is statistically correct: pleasant,\nbalanced, modern, clean, and utterly interchangeable. Authored design contains bias,\nconviction, and at least one decision an AI would have been nervous to make. You can use\nAI to build 95% of a site while deliberately removing every fingerprint below.\n\n## The two tests (pass both or go back)\n\n1. **The logo-swap test.** Remove the logo and company name. Can you still tell what\n   company this is? If no, it is template sludge.\n2. **The nervous test.** Is there anything here an AI would have been nervous to choose?\n   A strange typeface, an enormous sentence, aggressive whitespace, an unconventional\n   interaction, weird photography, a sharply specific opinion, a joke, a deliberately tiny\n   CTA, a brutalist section inside an elegant site, something culturally specific. If\n   nothing qualifies, it is polished but not authored.\n\n## Layout nos\n\n- Giant centered hero, vague headline, subheadline, two CTA buttons.\n- Headline of 6 to 10 words that says nothing concrete.\n- Every section on the same rhythm: eyebrow, huge heading, short paragraph, 3 cards.\n- Endless three-column feature-card grids.\n- Alternating left-text right-image sections with suspiciously perfect spacing.\n- Every card identical: same radius, padding, shadow, icon placement.\n- All sections roughly the same height. Everything mathematically centered, never composed.\n- No tension, overlap, asymmetry, or visual surprise anywhere.\n- \"Trusted by\" logo strip when the product has twelve users and a dream.\n- Decorative stat strips: 10K+ users, 99% satisfaction, 24/7 support.\n- FAQ accordion near the bottom as tribute to the AI gods.\n- Three pricing tiers, middle one \"Most Popular.\"\n- CTA banner before the footer repeating the hero.\n- Product / Company / Resources / Legal footer columns with dead links.\n- Everything in one max-width container, identical spacing increments (24/48/64/96).\n- Centered where left-aligned would feel human.\n- Mobile as \"desktop sections stacked vertically.\"\n\n## Styling nos\n\n- Purple-blue gradient. The ancient sigil of AI SaaS.\n- Dark navy with glowing violet or cyan blobs. Blurred radial gradients behind content.\n- Glassmorphism for no reason. Neon card borders. Huge border radii on everything.\n- Pill buttons everywhere. Pill labels above headings (\"POWERFUL FEATURES\", \"WHY CHOOSE US\").\n- Sparkles, stars, magic wands, brains, bots. Lucide icons with zero customization.\n- Every feature as a generic line icon in a softly colored rounded square.\n- Gradient text on one key phrase per headline.\n- Default giant sans (Inter-ish, Geist-ish, Manrope-ish). AI-gray body text.\n- Faint 1px borders on everything. Cards that lift 3px on hover to feel \"premium.\"\n- No hierarchy beyond huge heading, medium heading, gray paragraph. No memorable pairing.\n- Floating glowing dashboard illustrations. Fake browser mockups tilted 4 degrees.\n- Bento grids. Bento grids inside bento grids. Bento where nothing needs to be bento.\n- Animated hero orbs, grid-dot backgrounds, noise overlays manufacturing personality,\n  cursor-follow glow.\n- Every animation fade-up-on-scroll with the same stagger.\n\n## Copy nos\n\n- \"Transform / Revolutionize / Unlock / Supercharge / Empower / Built for the future.\"\n- \"Everything you need, all in one place.\" \"Seamlessly integrate.\" \"Effortlessly manage.\"\n- \"Take your X to the next level.\" \"Say goodbye to X and hello to Y.\"\n- \"Whether you're a small business or a growing enterprise.\"\n- \"Simple. Powerful. Secure.\" \"Work smarter, not harder.\" \"Your all-in-one solution.\"\n- \"Ready to get started?\" \"Join thousands of happy customers.\" \"Start your journey today.\"\n- The cursed construction: \"From X to Y, our platform helps you Z.\"\n- Every heading Title Case. Every paragraph exactly 2 to 3 lines.\n- Relentlessly positive, frictionless benefits. No opinion, no wit, no cultural texture,\n  no unusual metaphor, no evidence a human was ever annoyed by their own industry.\n- Nothing only this brand would say; swap the logo and it fits 400 startups.\n- \"Intuitive, seamless, robust, powerful, innovative, cutting-edge.\"\n- Testimonials that all sound alike, run the same length, use stock names with polished\n  headshots, and contain zero customer-specific detail.\n- FAQ answers that restate the marketing copy.\n\n## Information-architecture nos\n\n- Home / Features / Pricing / About / Contact regardless of what the business needs.\n- \"Solutions\" dropdown of arbitrary audience segments.\n- Separate \"Features\" and \"Why Us\" sections saying the same thing.\n- Blog and Resources pages that exist because websites apparently require them.\n- About page with a mission and no humans.\n- Talking about the product before the problem. Sections answering questions nobody asked.\n- Concrete information buried under aspirational language.\n\n## UX nos\n\n- Every primary button \"Get Started\", every secondary \"Learn More\". No contextual CTAs\n  (a button should say \"Show me my quote\", not \"Get Started\").\n- Buttons leading to generic destinations instead of the next obvious user action.\n- Forms asking too much. Generic empty states. Error states as an afterthought.\n- No edge-case thinking, no meaningful loading behavior.\n- Desktop polished, tablet mildly cursed, mobile inheriting desktop padding.\n- Hamburger menu with no reconsideration of priorities. Modals everywhere.\n- Tooltips explaining the obvious. Cards for absolutely everything. Settings as stacked cards.\n- Tables \"converted to cards\" on mobile instead of redesigned.\n- No power-user workflows, no recognition of repeated tasks, no click reduction around\n  the main job.\n\n## Dashboard nos\n\n- Four KPI cards: Revenue, Users, Conversion, Growth, each with a green +12.5% arrow.\n- Line chart, then bar chart beside pie chart, then Recent Activity table.\n- Sidebar: Dashboard / Analytics / Customers / Settings. Avatar bottom-left, bell\n  top-right, search bar nobody needs. \"Good morning, Alex\" with a wave.\n- Beautifully distributed fake data where every metric improves. Real operational software\n  contains ugly truths; a generated dashboard is a screenshot of the concept of productivity.\n\n## Image nos\n\n- Generated humans with suspiciously smooth skin. Woman smiling at absolutely nothing.\n- Fake offices of people pointing at screens. 3D blobs. Isometric floating interfaces.\n- Illustration style drifting between sections because the prompt changed.\n- Mood without function: every image pleasant, none informative. No real screenshots,\n  real people, real process, real mess.\n\n## Branding nos\n\n- Logo generated separately from the site. No motif beyond a gradient.\n- Harmonious but emotionally anonymous palette. No recurring graphic language, no\n  intentional constraints, no point of view.\n- The site could switch industries with a copy change.\n- Naming: noun+ly, noun+AI, Nexa/Nova/Flow/Sync/Pilot/Forge/Spark/Pulse/Aura/Lumina,\n  missing vowels, invented -ify words, anything copilot/agent. Plus a geometric sparkle\n  logo. Straight to jail.\n\n## The library fingerprint (shadcn/Tailwind, loved but lazy)\n\nrounded-xl, border, bg-card, text-muted-foreground, max-w-7xl mx-auto,\ngrid md:grid-cols-3 gap-6, icon+heading+paragraph card, badge above headline,\nButton size lg \"Get Started\", muted section alternating with white,\nshadow-sm hover:shadow-md, FAQ accordion, Sheet for mobile nav, Dialog for everything,\nTabs where tabs are not needed. If you can see the component library through the pixels,\nit is not designed yet.\n\n## How to apply\n\nRun this twice per build. Once before the first section is written, as the list of moves\nthat are off the table. Once before ship, as a review pass: walk each bucket against the\nactual pages, then run the two tests. A build fails the pass if several tells stack\ntogether, even if each one alone is defensible. And the positive obligation that follows\nfrom the nervous test: every build must contain at least one authored move, named out\nloud, that a generator would not have picked.\n\nRelated: [[anti-ai-craft-tells]] (art direction), [[vibecoded-code-tells]] (what the AI\nleft out of the code), [[base44-fingerprint-pass]] (de-templating a live Base44 build),\nand design-taste in the junk drawer (Megan's personal filter, which sits on top of this\nwhen the build is hers).\n\n===== Anti-AI craft tells (positive moves to check for) =====\n# How to not look AI-built\n\nFrom the Museum of Heartbreak research (2026-06-27). Megan said it plainly: tired of the\nAI-built look, the goal is work that lets her raise rates to MoMA/MET level. The tells below\ncame back consistent across grief, baroque-collage, and interaction research. Each is a\nmove you can actually ship.\n\n## The tells, and the fix\n\n1. Textures must be generated or scanned, never stock. Use SVG feTurbulence (Perlin noise\n   from nothing) plus feDiffuseLighting for paper grain, and feDisplacementMap for irregular\n   torn edges that never repeat. Scan real canvas, paper, and gold leaf and blend with\n   mix-blend-mode, not opacity alone. The moment a texture is a purchasable PNG, a judge can\n   place where it came from. If the grain, the tears, and the gilt are all generated or\n   scanned-from-real, no one can.\n\n2. Reject the uniform grid. A masonry grid is the default emotional posture of a database.\n   Arrange by adjacency or by an emotional axis (the 9/11 memorial placed names by\n   relationship). Even a light version, clustering by tag with hand-tuned anchors, reads as\n   intentional curation.\n\n3. Gilt and gold are punctuation, never wallpaper. One flat warm gold for type and hairline\n   rules. Reserve any metallic sheen for a scanned real gold-leaf texture masked into\n   letterforms. An animated gold gradient is the number one template tell.\n\n4. Pacing is craft. A slow, weighted transition (fade-through-black, a beat of stillness)\n   reads as human intent. Instant cuts and snappy default easings read as generated. Pacing\n   is the cheapest strong signal available.\n\n5. Typography is the design, and the font choice is a fingerprint. Playfair Display is the\n   SaaS-template default; it is a tell. Reach instead for Ogg, Canela, GT Sectra, Domaine,\n   or Reckless, paired against a stark grotesque for tension. For a ransom-note or cut-paper\n   layer, never buy a ransom font; scan real letterforms and collage them over the clean\n   system. The irregularity is what reads human.\n\n6. Commit to the bit. Half-committed pastiche reads as a mistake, not a choice. See\n   [deliberate-pastiche](deliberate-pastiche.md): when the aesthetic is the assignment, go\n   all the way.\n\n## Why it matters\nTools collapsed the execution gap, not the taste gap. Anyone can generate a site in an\nafternoon now, so the only moat is creative direction. These moves are how the taste shows\nup in the pixels, not just in the brief.\n\n===== Design taste (PREFERENCE — apply loosely) =====\n# Your design taste\n\nThe single most useful page in the bible. Read it before choosing anything visual.\n\n## What you love\n- The Notion / Are.na feeling: warm, slightly analog, readable, design that gets out of the way.\n- Functional beauty over decorative beauty. The page does its job first, looks good second, and looking good comes FROM doing the job well.\n- Warm tones over cold tones.\n- Typography-driven design over effects-driven design. The type does the work.\n- Two fonts only, corrected 2026-08-13 on her portfolio: IBM Plex Serif for titles, Jost for everything that is not a title. The earlier all-Plex stack (Serif, Sans and Mono as three voices) read to her as \"why are there so many fonts\". Serif titles stay sacred; the body voice is Jost.\n\n## What you hate (hard no)\n- Playfair Display. Specifically. Do not reach for it.\n- \"Vibe code\" colours: trendy dark mode with neon accents, purple and pink gradients, glassmorphism. The default look of a tool that was told \"make it pretty.\" You can spot it instantly and it reads cheap to you.\n- Decoration for its own sake. Effects standing in for ideas.\n- Tilted, scattered, or staggered layouts (caught 2026-08-09 on your own portfolio: \"I don't like the disorganised this\"). Handmade lives in texture: grain, crayon strokes, tape, scribbled notes. Layout stays aligned. A tape strip at a slight angle on a straight print is fine; the print itself never tilts.\n- Line art. Outlined icons (lucide checks, chat bubbles, sparkles, arrow glyphs, padlocks) are decoration standing in for ideas. Stated as an established allergy 2026-08-13 (\"what did we say about being allergic to line art\"). Where an arrow earns its place, set it as type: a text arrow for internal moves and an up-right text arrow for external links. Functional controls (menu, close, theme toggle) may keep their icons.\n- Buttons and paragraphs that do not align. Parallel cards must pin their buttons to one shared baseline no matter how long the content above runs. \"Every single part of it needs to be aligned\" (2026-08-13) is the same law as the no-tilt rule: alignment is sacred.\n\n## How to use this\nWhen a build needs a look, the first move is to run the options through this page. If a mockup drifts toward neon-on-dark, gradient soup, or Playfair, it is wrong before you even see it, kill it early. If it feels like a warm, well-set, quietly confident Notion or Are.na page, you are in the right room.\n\nThis is the \"looks like it does not matter but matters very much\" shelf you asked for. It matters most.\n\n===== ARS house stance (discipline binding, preference a guide) =====\n# ARS house stance on the inherited taste\n\nThis vault came as a gift and [design-taste](design-taste.md) reflects its original\nowner's preferences. ARS policy, set 2026-09-13:\n\n- The DISCIPLINE layer is binding: the divine hell nos, design-system-before-prompting,\n  the code tells, structure before polish, the two tests (logo-swap, nervous). Run them\n  on every build.\n- The PREFERENCE layer (palettes, the specific font law, warmth-over-dark) is a guide to\n  good aesthetics, not a rule. Follow it loosely, deviate deliberately, and log the\n  deviation here so the vault becomes ours over time.\n\n## ARS calls logged so far\n\n- Dark multi-world showcase (the ARS website) is a chosen genre, not a vibe-code default.\n  Judged under deliberate-pastiche rules: light needs a source, intent must be visible.\n- Alignment is sacred: adopted as-is. No tilted layouts; handmade lives in texture.\n- Line-art allergy: adopted for decoration. Lucide stays for functional controls only.\n- Plex Mono as a data voice (statuses, bearings, slash commands, morse): an ARS addition\n  beyond the two-font law. Deliberate, scoped, kept.\n- Fonts for the ARS site: undecided. Current stack is Archivo display plus Newsreader\n  serif titles plus Plex Mono data. The vault's Plex Serif plus Jost law is a candidate,\n  not a requirement. Decide by looking, not by rule.\n- Playfair Display ban: kept. It is a template tell independent of anyone's taste.\n- Warm-over-cold: not adopted as law. ARS product brands are navy-dark by choice; the\n  warmth rule applies where the register fits (the paper close, long-form pages, docs).";
// <<<END DESIGN_BIBLE>>>

// The review CONTRACT (stable, hand-maintained): the reviewer role, HOW to apply
// the bible's layers, the verdict rubric, and the exact JSON to return. The WHAT
// — fingerprints, tests, taste — comes from DESIGN_BIBLE above (synced from source
// and treated as the authority).
const DESIGN_REVIEW_SYSTEM = `You are Byte-ling in art-director mode — a senior designer running a house design review on a page the user built. You judge; you do not redesign. Your only output is the JSON object specified below. Voice: direct, warm but brief, no padding — a failed test is failed, not "an opportunity". Three real findings beat ten manufactured ones. If the page is genuinely good, say so and keep the findings list short.

THE CORE DISTINCTION is generated vs AUTHORED — not human vs AI. Generated design is statistically correct: pleasant, balanced, modern, interchangeable. Authored design carries bias, conviction, and at least one decision a generator would have been nervous to make.

YOUR RULEBOOK is the DESIGN BIBLE at the end of this prompt (synced from the house source; it is the authority on WHAT to check — read it before judging):
 • Apply its DISCIPLINE layer STRICTLY — the divine hell-nos (the generated-vs-authored blocklist, section by section) and the two tests:
    - LOGO-SWAP: cover the logo/name — can you still tell whose site this is? If no → template sludge.
    - NERVOUS: name one decision a generator would have been nervous to choose. If nothing qualifies, the test FAILS and that is the headline finding.
   Several fingerprints stacked = a fail even if each alone is defensible. Also credit the positive craft moves the bible lists that are MISSING (medium severity).
 • Apply its PREFERENCE layer LOOSELY, per the ARS house stance in the bible: palettes, the specific font law, and warmth are a guide, not law. Where a build diverges from house preference, raise it as a LOW-severity question, never a HIGH violation — never fail a page for being dark or for a font choice alone. (Playfair Display stays a real tell — that one is discipline.)

EVIDENCE RULE (non-negotiable): every finding MUST cite evidence — a specific number from the census, or a concrete observation from the screenshot ("the three feature cards share one radius/shadow/icon slot", "headline is 8 vague words"). Never assert a fingerprint you cannot point to. With no census (screenshot-only), grade from the screenshot and say the evidence layer is thinner — never invent census numbers.

VERDICT RUBRIC:
 AUTHORED: passes both tests; distinctive; few/no stacked fingerprints.
 POLISHED BUT GENERATED: clean and competent but the nervous test fails and/or several fingerprints stack — no conviction.
 TEMPLATE SLUDGE: fails the logo-swap test; fingerprints everywhere.

OUTPUT — return ONLY this JSON object, no prose, no code fences:
{
  "verdict": "AUTHORED" | "POLISHED BUT GENERATED" | "TEMPLATE SLUDGE",
  "verdictLine": "one line of rationale",
  "tests": {
    "logoSwap": { "pass": true|false, "note": "one line" },
    "nervous":  { "pass": true|false, "note": "name the authored move, or say none exists" }
  },
  "findings": [
    { "severity": "HIGH"|"MEDIUM"|"LOW", "finding": "the defect, one sentence", "evidence": "census figure or screenshot observation", "fix": "the concrete move" }
  ],
  "nervousSuggestion": "ONE specific authored move for THIS build — only when the nervous test fails; otherwise empty string",
  "nextAction": "the single highest-leverage fix to do first"
}
Rank findings most-severe first. HIGH = a stacked hell-no fingerprint or a failed test; MEDIUM = a missing craft move or taste drift; LOW = polish or a preference-layer question. Do not pad. Output the JSON and nothing else.

===== DESIGN BIBLE (current, synced from claude-skills — the authority on WHAT to check) =====
${DESIGN_BIBLE || '(bible not synced yet — run scripts/sync-design-bible.mjs; grade from the discipline rules above)'}`;

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);

    const user = await base44.auth.me();
    if (!user?.email) {
      return Response.json({ error: 'Authentication required' }, { status: 401 });
    }

    // Bring-your-own-key — identical resolution to claude-chat.
    const keys = await base44.asServiceRole.entities.ProviderKey.filter({
      owner_email: user.email,
      provider: 'anthropic',
      status: 'active'
    });
    const providerKey = keys?.[0];
    if (!providerKey?.api_key) {
      return Response.json(
        { error: 'Add your Anthropic API key to use the assistant', code: 'no_provider_key' },
        { status: 400 }
      );
    }
    const apiKey = providerKey.api_key;

    let body: Record<string, unknown> = {};
    try {
      body = await req.json();
    } catch {
      return Response.json({ error: 'Expected a JSON body' }, { status: 400 });
    }

    const url = typeof body.url === 'string' ? body.url.slice(0, 300) : '';
    const image = parseImageInput(body.screenshotBase64);
    let censusText = '';
    if (body.census != null) {
      censusText = (typeof body.census === 'string' ? body.census : JSON.stringify(body.census)).slice(0, MAX_CENSUS_CHARS);
    }

    if (!image && !censusText) {
      return Response.json(
        { error: 'Nothing to review — need a screenshot and/or a style census' },
        { status: 400 }
      );
    }

    // Build the review turn: the evidence (census + url) as text, the page as an
    // image. Screenshot-only is allowed; the prompt tells the model to say so.
    const parts: string[] = [];
    parts.push(url ? `Page under review: ${url}` : 'Page under review: (url not provided)');
    if (censusText) {
      parts.push(`Style census (the evidence layer — cite these numbers):\n${censusText}`);
    } else {
      parts.push('No style census was provided — grade from the screenshot alone and say the evidence layer is thinner.');
    }
    parts.push('Review this page now. Return only the JSON object.');

    const content: unknown[] = [];
    if (image) {
      content.push({ type: 'image', source: { type: 'base64', media_type: image.media_type, data: image.data } });
    }
    content.push({ type: 'text', text: parts.join('\n\n') });

    const anthropic = new Anthropic({ apiKey });

    let final;
    try {
      final = await anthropic.messages.stream({
        model: MODEL,
        max_tokens: MAX_TOKENS,
        thinking: { type: 'adaptive' },
        output_config: { effort: REVIEW_EFFORT },
        system: DESIGN_REVIEW_SYSTEM,
        messages: [{ role: 'user', content }]
      }).finalMessage();
    } catch (e) {
      const status = (e as { status?: number })?.status;
      if (status === 401 || status === 403) {
        await base44.asServiceRole.entities.ProviderKey.update(providerKey.id, { status: 'invalid' }).catch(() => {});
        return Response.json(
          { error: 'Your Anthropic key was rejected — please re-enter it', code: 'invalid_provider_key' },
          { status: 400 }
        );
      }
      throw e;
    }

    const raw = (final.content || [])
      .filter((b: { type?: string }) => b.type === 'text')
      .map((b: { text?: string }) => b.text || '')
      .join('')
      .trim();

    // The prompt asks for bare JSON, but strip a stray ```json fence just in case.
    const jsonText = raw.replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/i, '').trim();
    let review;
    try {
      review = JSON.parse(jsonText);
    } catch {
      return Response.json(
        { error: 'The review came back unreadable', detail: raw.slice(0, 300) },
        { status: 502 }
      );
    }

    return Response.json({ review });
  } catch (error) {
    console.error('designReview failed:', error);
    const detail = (error instanceof Error ? error.message : String(error)).slice(0, 180);
    return Response.json({ error: 'The design review could not run', detail }, { status: 500 });
  }
});
